//
// Created by PC on 13/05/2022.
//

#ifndef FURAMAPROJECT_READANDWRITECUSTOMER_H
#define FURAMAPROJECT_READANDWRITECUSTOMER_H


class ReadAndWriteCustomer {

};


#endif //FURAMAPROJECT_READANDWRITECUSTOMER_H
